### ISSUE TITLE
Maxima matrices are not rendered properly.

### ISSUE THREAD

**Issue by WetHat** [robert-dodier/maxima-jupyter#41] opened 2018-11-18 08:05 UTC
While other Maxima expressions are rendering just ok, this is not the case with matrices.
Please see screenshot below:
<img width="665" alt="Bad Math Rendering" src="https://user-images.githubusercontent.com/10697674/48669975-d081bb80-eb0f-11e8-8cb6-bb064ccf927f.png">

I've tried this with different versions of MathJax and Anaconda environments.  None of them improve matrix rendering unfortunately.

WetHat

PS: Maxima in a Jupyter notebook is an excellent idea!

**Comment by robert-dodier** [comment] 2018-11-24 00:36
Hi, thanks for your interest in Maxima-Jupyter. May I ask for what purpose you are using it?

About matrix display, the problem is that Maxima is trying to output something which is acceptable to different versions of LaTeX. I don't understand why that output is causing trouble -- when I generate output from `tex` in the Maxima console and put it in a file and run the `latex` command on that, the output looks correct. Also, in Jupyter, if I choose File >> Download as >> PDF via LaTeX, again, that output looks correct.

Does anyone have an idea as to why Jupyter doesn't like the matrix output?

As a workaround, try this: `load("mactex-utilities");` which loads exactly 2 items. (1) revise TeX output for quotients to use `\frac` instead of `\over`. (2) Revise TeX output for matrices to only use `\begin{pmatrix}` and `\end{pmatrix}` (no attempt to accommodate anything else). I find that after I do that, matrix display looks correct in Jupyter.

**Comment by robert-dodier** [comment] 2018-11-24 18:00
My guess is that MathJax is confused by the tex output which contains some conditional output. I've resolved this problem by loading mactex-utilities in load-maxima-jupyter.lisp. See commit de1691d. Closing this issue, hope this helps!

**Closed by robert-dodier** 2018-11-24 18:00 UTC

**Comment by robert-dodier** [comment] 2018-11-28 22:09
On Tue, Nov 27, 2018 at 6:27 AM Peter Ernst <notifications@github.com> wrote:

> I'm developing supervised machine learning algorithms in the field of computational geometry such as algorithms to recognize analytical surfaces in point clouds.

Hmm, that sounds very interesting. I have done some work in machine
learning also. If you have any reports or publications I would be very
interested to read it.

>  Currently I'm switching over to Jupyter because it is a much richer environment than wxMaxima. Also Jupyter notebooks have a much wider reach than wxMaxima notebooks.

Yes, I think Jupyter is very useful environment. I recently was
reading about JupyterLab which integrates several items, including the
notebook, into a single environment. I think I will try that soon.

Good luck, and all the best,

Robert.
