### ISSUE TITLE
Creation of maxima image

### ISSUE THREAD

**Issue by jvlatzko** [robert-dodier/maxima-jupyter#5] opened 2017-06-23 18:02 UTC
Hi, 

after adding a line `(load "~/quicklisp/setup.lisp")` into `load-maxima-jupyter.lisp` so that it actually loads quicklisp, I am getting this error message: 

> (%i2) :lisp (load "load-maxima-jupyter.lisp")
> now ASDF:*CENTRAL-REGISTRY*=("/home/vincent/Downloads/maxima/src/")
> While evaluating the form starting at line 17, column 0
> Maxima encountered a Lisp error:
> 
 > System "maxima-jupyter" not found

Note that I used `maxima -l sbcl` since the -ccl option doesn't work on my machine (`/usr/bin/maxima: line 185: exec: openmcl: not found`) 

All in all a very painful experience - while I really, _really_ appreciate the work, documentation is really bad and IMHO incomplete.

**Comment by robert-dodier** [comment] 2017-06-24 20:12
Yes, the documentation is bad and incomplete. Sorry about that. I hope it is useful in some way anyhow.

My advice is to go ahead and install CCL and try again. Getting maxima-jupyter to work with SBCL probably requires some specific debugging. 

I don't know if I mentioned a specific CCL version in the notes for this project -- if not, try version 1.9. I believe that's the version I've been working with and therefore more likely to work for you.

**Comment by jvlatzko** [comment] 2017-06-26 14:52
FWIW I've tried that on a fresh ubuntu vm. ccl with bells and whistles, quicklisp, jupyter and maxima brandnew. 

The results didn't terribly differ. At some point I checked out `/usr/lib/maxima/5.38.1` to find a the folder `binary-gcl`, so I went ahead and installed and used `gcl`. 

That gave me something new, 
`(%i2) :lisp (load "load-maxima-jupyter.lisp")

Maxima encountered a Lisp error: 

Error: 
Fast links are on: do (si::use-fast-links nil) for debugging
Signalled by MAKE::NEW-REQUIRE.
SIMPLE-ERROR: The slot MAKE::COMNPONENT is unbound in the objecdt #<MAKE:MISSING-SYSTEM.0>. 

Broken at MAKE:MISSING-COMPONENT-COMPONENT. Type :H for Help. 
    1 Maxima top-level
    2 Maxima top-level
    3 Maxima top-level
    4 Return to top-level. 
MAXIMA>> `

I don't know whether this helps, YMMV... 

Also, Cl-jupyter's kernel deathlooped. I installed it after nearly giving up, thinking that maybe this would shed some new light. What I'm supposed to do with cl-jupyter with respect to maxima-jupyter is still a mystery to me, but maybe that script magically solves all that, if it runs on a correctly configured machine.

**Comment by robert-dodier** [comment] 2017-06-26 16:58
maxima-jupyter requires some code which is specific to the Lisp version -- stuff for socket and process control if I remember correctly. So changing from CCL to SBCL or GCL or anything almost certainly can't work without additional specific debugging and development for the new Lisp version. I'm sorry that this makes things more difficult, believe me, I wish it weren't so.

CL-Jupyter is the basis of maxima-jupyter but it is not required to install CL-jupyter in order to use maxima-jupyter.

**Comment by robert-dodier** [comment] 2017-06-29 22:57
For the record, I installed maxima-jupyter on a new Mint Linux (Ubuntu-based) system, according to the instructions I wrote before, and it was really, really painful, and I almost gave up, but I did get it working finally. The difficulties were caused by different versions of things outside of maxima-jupyter itself: 32 bit vs 64 bit CCL, difficulties installing some Jupyter/IPython stuff, difficulty with libzmq (messaging). 

It does finally work, so it's at least plausible that I could devise an exact recipe which is more likely to succeed. I will try to take the time to sort it out and write up a guide for others. In the meantime I will close this message thread since you have indicated you don't plan to spend more time on it.

**Closed by robert-dodier** 2017-06-29 22:57 UTC
